
Guías de usuario
--------------------------------

.. toctree::
   :maxdepth: 2

   quickstart
   models
   queries
   pagination


Referencia del API
--------------------------------
¿Buscando información sobre una función específica? ¿Quieres darte una idea de como está organizado el código? Esta parte de la documentación es para ti.

.. toctree::
   :maxdepth: 2

   api


Notas adicionales
--------------------------------

.. toctree::
   :maxdepth: 2

   about
