py_library(
    name = 'sub_sqlalchemy_wrapper',
    srcs = [
        '_compat.py',
        'helpers.py',
        '__init__.py',
        'main.py',
        'paginator.py',
    ],
    deps = [
    
    ],
)
